### ISSUE TITLE
Remove filtering etc from API version 1.0

### ISSUE THREAD

**Issue by bobjolliffe** [facilityregistry/fred-api#1]
I suggest we omit property filtering, counting, pagination, search and sorting from the initial version of the facilities API.

This will simplify implementation and allow us to come to agreement on the API more quickly. Adding these refinements can be done at a later date in a backwards compatible way.

I am not sure about filtering by updated_since. If we want to allow consumers of the API to maintain a mirror of the facilities so that they can operate without connectivity, then we may need a way to allow them to check for changes so they can selectively update. This is the case in Uganda.

**Comment by ctford** [comment]
From [Carl](https://github.com/litlfred):

We will also need updated_since for the Provider Registry in Rwanda.
Cheers,
-carl

**Comment by rowenaluk** [comment]
Agree with keeping updated_since.

Also fine with skipping counting, pagination, search, and sorting. 

For property filtering, let's support 'active=True' and 'active=False'. Am fine to revisit the rest later.

**Comment by edjez** [comment]
Agree on punting for when we have a more iterative community process to deal with all the can of worms

**Comment by mberg** [comment]
parameters supported 

Active
Update Since
