### ISSUE TITLE
Question about Counting

### ISSUE THREAD

**Issue by ghost** [facilityregistry/fred-api#10]
Another question, what is the purpose of the count operation? I'm trying to come up with some samples/description for count and the only use case I can think of is getting the total number of facilities matching a particular filter (example, for doing a progress bar). Is this correct?

If so, may I ask the rationale for doing it this way? It seems like a pretty chatty.

GET /facilities/count.xml?name=Good%20Health
GET /facilities.xml?name=Good%20Health

Is there a use case where a client application would want to count the number of facilities without actually getting them? Maybe I'm just stuck on a query use case :)

Perhaps adding the meta-data for the query results might be a better solution. For example (adapted from the current docs)

```
 <fac:queryAck>
     <fac:current>2</fac:current>
     <fac:offset>0</fac:offset>
     <fac:total>20</fac:total>
 </fac:queryAck>
```

Cheers
-Justin

**Comment by edjez** [comment]
Counting is not for progress bars or the likes; consider the following scenarios:
- doing a heatmap of facilities by lat/long squares; or histograms or other stat queries
- doing some stats of facilities that do X versus facilities that do Y
- doing a bandwidth-efficient query of "are there facilities at all that conform to criteria ABC"

**Comment by edjez** [comment]
Postponing from 1.1/current version discussion

**Comment by mberg** [comment]
Closing will discuss later if it comes up again.
