### ISSUE TITLE
Explicitly document lat/long order

### ISSUE THREAD

**Issue by ctford** [facilityregistry/fred-api#13]
In the geolocation section, we use GeoJson derived coordinates:

```
coordinates: [-1.6917, 29.5250]
```

The spec doesn't say whether the first number is latitude or longitude. This should be added briefly to avoid ambiguity.
- Chris, Morten, Bharti

**Comment by mberg** [comment]
Cool. Was following geojson. Are you cool with coordinates as a field name?

**Comment by ctford** [comment]
Yes, following GeoJson is fine for both the `coordinates` name and the structure of the points. Would just be good to make sure everyone knows it's not long/lat. :-)

**Comment by mberg** [comment]
updated

**Comment by mortenoh** [comment]
According to the spec, the order _is_ `[lng, lat]`

http://www.geojson.org/geojson-spec.html#appendix-a-geometry-examples

**Comment by mberg** [comment]
k that's really weird as having else is lat, long.  I guess in terms of x,
y then it's right.  Will change

On Sun, Dec 9, 2012 at 2:31 PM, Morten Olav Hansen <notifications@github.com
