### ISSUE TITLE
Dates should have a timezone

### ISSUE THREAD

**Issue by ctford** [facilityregistry/fred-api#15]
For e.g. Created At, we say we should use ISO 8601. However, this spec doesn't mandate a timezone. When there is no timezone, "local" time is used, which isn't suitable for a client/server app.

Could we mandate specifying a timezone? Or at least suggest one?
- Chris, Morten, Bharti

PS The wikipedia link to ISO 8601 has a trailing slash, which breaks it.

**Comment by mberg** [comment]
Fixed link thanks

For now should we just append a Z on there or should I provide a more illustrative example?

**Comment by ctford** [comment]
We think that timezone should be mandatory, and UTC preferred.

**Comment by mberg** [comment]
Ok I updated the docs but I'll make that statement explicit too.

So everything is normalized to UTC basically?

**Comment by ctford** [comment]
Yes, I think that's the path of least confusion.

**Comment by ctford** [comment]
The date example in in the dynamic properties section doesn't have a timezone.

**Comment by mberg** [comment]
thanks fixed
