### ISSUE TITLE
Use "list" property type instead of "select"

### ISSUE THREAD

**Issue by ctford** [facilityregistry/fred-api#16]
The "Implementation Specific Properties" has several types that custom types can be built out of. One of them is "select", which is a little confusing as it appears to relate to a UI element, perhaps HTML?

Could this be specified as a list that contains instances of the other simple types?

Or at least could the meaning of this type have more explanation?
- Chris, Morten, Bharti

**Comment by mortenoh** [comment]
+1

**Comment by mortenoh** [comment]
It would be nice with a clarification of whether something like this:

``` javascript
"properties": {
  "services": [ { "id": 123, "name": "ABC" } ]
}
```

Is allowed for the `list` type (basically objects within lists).

**Comment by ctford** [comment]
We've decided to use a structure similar to Morten's comment above to describe the hierarchy of facilities in Uganda. Each step in the hierarchy needs to be an object because it has a url, id and name, so we can't do it with a simple list of strings.

As far as we understand currently, this is legal.

**Comment by mberg** [comment]
Could you copy and paste an example?

**Comment by ctford** [comment]
Following up with Morten RE the exact format of the example.

**Comment by mberg** [comment]
From ed:

I think so.. but hard to decide given the example
"services" specifically is an example of a multi-select value; so you
should be able to get multiple "pairs" of 123:ABC   456:XYZ
maybe i misunderstood the question?

Will discuss quick on the call today and have resolution on this.

Thanks,

Matt

**Comment by mortenoh** [comment]
This is how our properties block look in DHIS 2 today. A live example can be seen on

http://apps.dhis2.org/dev/api-fred/v1/facilities/agM0BKQlTh3.json

(login: system, password: System123)

``` javascript
properties: {
level: 4,
parent: "hRZOIgQ0O1m",
hierarchy: [
{
id: "H1KlN4QIauv",
level: 1,
name: "National",
url: "http://apps.dhis2.org/dev/api/organisationUnitLevels/H1KlN4QIauv"
},
{
id: "wjP19dkFeIk",
level: 2,
name: "District",
url: "http://apps.dhis2.org/dev/api/organisationUnitLevels/wjP19dkFeIk"
},
 {
  id: "tTUf91fCytl",
  level: 3,
  name: "Chiefdom",
  url: "http://apps.dhis2.org/dev/api/organisationUnitLevels/tTUf91fCytl"
 },
 {
  id: "m9lBJogzE95",
  level: 4,
  name: "PHU", 
  url: "http://apps.dhis2.org/dev/api/organisationUnitLevels/m9lBJogzE95"
 }
 ],
 dataSets: [
  "SF8FDSqw30D",
  "pBOMPrpg1QX",
  "N4fIX1HL3TQ",
  "BfMAe6Itzgt",
  "TuL8IOPzpHh",
  "EDzMBk0RRji",
  "eZDhcZi6FLP",
  "OsPTWNqq26W",
  "Rl58JxmKJo2",
  "joWPywO7yOJ",
  "aLpVgfXiz0f",
  "lyLU2wR22tC",
  "QX4ZTUbOt3a"
 ]
}
```

**Comment by mberg** [comment]
Lists can contain complex objects.

"properties": {
  "services": [ { "id": 123, "name": "ABC" } ]
}

**Comment by edjez** [comment]
Select-single, IMO should return the scalar that is the Code of the selected value, formatted as any scalar

Multiple-select should return the vector of codes of the selected value(s); 

Other complex types may need to return vectors or complex documents to best represent them, including lists of complex objects
