### ISSUE TITLE
Query: URL format?

### ISSUE THREAD

**Issue by ctford** [facilityregistry/fred-api#17]
The spec is inconsistent as to whether `.json` appears on the end of URLs. For _updating_ a facility, there's no `.json`, but for _reading_ them, there is.

Also, in the example, the URL to the facility doesn't have the extension.

This seems inconsistent.
- Chris, Morten, Bharti

**Comment by mberg** [comment]
I agree.   For some reason, there was an argument about leaving the .json
of the URL.  I think that's when we were supporting both xml/json.

I'd prefer to have it be .json too.  Is there any reason you can think of
(based from what I just said) not to do that?

**Comment by mberg** [comment]
K updated for now.  Agree it's more consistent.  We can amend if we get push back.

**Comment by ctford** [comment]
Did you intend to update the URL in the "Adding / Updating Facilities" section to add the .json? The one for creating facilities? It's still missing the extension.

The issue around putting .json on the URLs or not was (I think) related to the discussion over content negotiation. Having multiple URLs for the same resource can make things ambiguous for a service that's linking to a facilities registry.

That's not an issue when we have only a single format, which is partly why I prefer having a single format (though there are some, including Morten, who value supporting both).
