### ISSUE TITLE
Meta Summary Data?

### ISSUE THREAD

**Issue by mortenoh** [facilityregistry/fred-api#18]
So what is the point of this? It seems to be related to paging, but I see that the paging parameter is now removed.

Does it make sense to have this anymore, or should it be removed? or at least the example should be changed to an actual use-case of this block.

**Comment by mberg** [comment]
It's related to paging.  Sorry I missed that.  Will move to future features
for now.

On Tue, Dec 4, 2012 at 3:15 PM, Morten Olav Hansen <notifications@github.com

**Comment by mberg** [comment]
moved to future features for now.
