### ISSUE TITLE
/facilities.json?properties=all 

### ISSUE THREAD

**Issue by mortenoh** [facilityregistry/fred-api#19]
It's not specified, but should you be able to do properties=name here? and so on? is it basically a boolean, so maybe it should be changed to properties=true ? (same as active)

**Comment by mberg** [comment]
We had that but it a properties filter was voted to be pushed to the next
addition.

We could roll this into an early 1.1 if you want to implement it.

On Tue, Dec 4, 2012 at 3:23 PM, Morten Olav Hansen <notifications@github.com

**Comment by mortenoh** [comment]
It think it would be better (for this release) to either change it to being a boolean? or maybe even default to include all properties?

I don't really care about the filtering aspects of it, but I will need the properties included.

**Comment by mberg** [comment]
Oh this isn't a filter but rather defines the response of the properties.

Ok let me improve documentation.

Just to be clear.  you're proposing

properties=true

this will return all the items in the properties block.  Omitting it or
properties=false will just return the core properties.

For selected properties we could do

properties=field1,field2,field3

Would that work for you?

On Tue, Dec 4, 2012 at 3:27 PM, Morten Olav Hansen <notifications@github.com

**Comment by mortenoh** [comment]
Yeah, I was proposing that.

Ok, so I was assuming this included core properties. But this is only for additional properties? so the core properties would always be included?

**Comment by mberg** [comment]
yes core always included.  Any reason why they shouldn't?

If we are worrying about performance in the future we can add a way of
explicity defining the fields you only want

On Tue, Dec 4, 2012 at 3:31 PM, Morten Olav Hansen <notifications@github.com

**Comment by mortenoh** [comment]
No, I think that's OK. I think maybe the documentation could be a bit clearer (calling it additional properties, or something to that effect).

Ok, seems a bit clearer then.

**Comment by mortenoh** [comment]
Of course, you have the potential pitfall that you have a property called 'all'.

**Comment by mberg** [comment]
In that case would properties=all be better then the boolean?

On Tue, Dec 4, 2012 at 3:35 PM, Morten Olav Hansen <notifications@github.com

**Comment by mortenoh** [comment]
Not really. I think the wording properties is a bit off, because it seems like you are asking for any property. Say you have properties=name, which would mean the name part of the properties block, and not the facility name. Also, if you have properties=all, and properties: { "all": true, ... } how would that be handled? (when filtering is implemented).

**Comment by mortenoh** [comment]
I think, ideally I would like something like this supported (which is similar to what Google is doing):

`?fields=id,name,properties:name,properties:services`

I don't think we need it deeper than that, although it would be neat to have something like:

`?fields=id,name,properties:name,properties:services(name)`

I don't really see why a query parameter just for _properties_ was added.

**Comment by rowenaluk** [comment]
i vote for making properties a boolean field.

i have a slight preference that the provider should, by default, return all properties, as I think this will be the more common use case. but i don't feel strongly about this. 

i also vote for renaming this field, to "core_properties" or "all_properties", depending on what it does. 

in answer to the other questions, when filtering is implemented, if we had a property like {"all":true}, one way to do it is by specifying "property=true". we should then specify a set of reserved keywords which cannot be used to name properties i.e. 'property'. also, i'm not a fan of requiring each client to specifically list out whatever field they are interested in.

**Comment by mortenoh** [comment]
I think we can just have `allProperties=boolean` for now (default `true`). And reopen this issue for 1.1.

**Comment by mortenoh** [comment]
I see you added `allProperties` which is good.

I'm not so happy about the `fields` filtering however. It seems like its mixing core properties with the properties block, which makes it very confusing. If we really want this kind of simplified filtering, I think it should apply to the properties block only.

I still like my proposal better. ;-)

**Comment by mberg** [comment]
Ok so this means the core properties are always returned?

I didn't add support for subobjects yet.  Should we include that now?

**Comment by mortenoh** [comment]
I'm not sure. I think its a waste of a good query parameter name to use it only for the properties block. Right now, getting all the core properties, but I see in the very near future that more core props will be added, grouping and services seems like obvious choices, together with contact information.

Yes, we are already using subobject in our DHIS 2 implementation.

``` javascript
{
    "id": "XtuhRhmbrJM",
    "name": "Baiama CHP",
    "active": true,
    "url": "http://localhost:8080/api-fred/v1/facilities/XtuhRhmbrJM",
    "createdAt": "2012-12-09T19:28:43.719+0000",
    "updatedAt": "2012-12-09T19:28:43.719+0000",
    "coordinates": [
        -10.9677,
        8.5167
    ],
    "identifiers": [
        {
            "id": "OU_233331",
            "context": "DHIS2_CODE",
            "agency": "DHIS2"
        }
    ],
    "properties": {
        "level": 4,
        "parent": "M2qEv692lS6",
        "hierarchy": [
            {
                "level": 1,
                "name": "National"
            },
            {
                "level": 2,
                "name": "District"
            },
            {
                "level": 3,
                "name": "Chiefdom"
            },
            {
                "level": 4,
                "name": "PHU"
            }
        ],
        "dataSets": [
            "SF8FDSqw30D",
            "pBOMPrpg1QX",
            "N4fIX1HL3TQ",
            "QX4ZTUbOt3a"
        ]
    }
}
```

**Comment by mberg** [comment]
Sorry to clarify, the filter is for ANY property not just specified. So
both core and specified.

That's what I intended. Maybe the docs are confusing.

**Comment by mberg** [comment]
Ok can you please provide me a blurb description for sub-object and I'll
add it to the api docs.

**Comment by mortenoh** [comment]
Is there any reason why we are specifying what JSON is in our spec? can't we just point to http://www.json.org/? It is all there.

**Comment by mberg** [comment]
We can link to that.

A lot of laypeople don't understand what a sub-object is.  So we should
explain that out a bit.

**Comment by mortenoh** [comment]
Regarding the core vs properties block, I did understand that it was picking from both places, I'm just saying its confusing, what if I add services to the properties block today, and tomorrow we add services as a core property, which one should it pick? I think if people don't want what I suggested, I think saying `fields=field1, field2`, etc will only apply to the properties block is OK for now, but it will hurt us later, when we add too many core properties, and filtering on that will become something very real.

**Comment by mortenoh** [comment]
I don't know who our target developer audience is, but if they don't understand what objects are in JavaScript, they have more urgent issues than reading our API documentation.

**Comment by mberg** [comment]
We definetly want to be able to filter both.

Should we want to do something like

fields=name,properties:numBeds?

**Comment by mortenoh** [comment]
I would like that, but I'm not sure everyone agrees. :-) that would make it possible to add further filtering in the future, this would also make it possible so that we in the future can add support for further filtering.

**Comment by mberg** [comment]
Is what I just sense the way you would do it?

I like that it provides a clear distinction between the core indicators and
those in the property block.  It also copies the structure of the json
which makes it pretty intuitive.

**Comment by mortenoh** [comment]
Yes, I think Chris sent you the Apigee PDF ? This kind of filtering is exactly what Google is doing, and it is very simple, and very flexible at the same time.

**Comment by mberg** [comment]
I sent out the APIgee or maybe we both did :)

Ok I'll change it to reflect this.

**Comment by mortenoh** [comment]
I guess we both did :)

Great!

**Comment by bobjolliffe** [comment]
Don't try and explain this kind of stuff in the spec.  Save it for a
tutorial document if need be.

**Comment by mberg** [comment]
agreed.  updated docs please let me know if they look ok.

**Comment by mortenoh** [comment]
Looks good to me.
