### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by mberg** [facilityregistry/fred-api#21]
# Pagination

```
/api/features.json?limit=25&offset=50
```
- **limit**: the amount of records to return in a result.  Default = ??
- **offset**: the offset of the search result.  Facilitates pagination
- **paging=false**: turns pagination off

**Comment by ghost** [comment]
Hi Matt, 

I think this is a good feature but I don't see the usefulness of paging=false. I would say the default is to return all results for a particular query do query limitation / continuation when ?limit is supplied (as limit implies that the client will be paginating)

**Comment by bobjolliffe** [comment]
+1

**Comment by edjez** [comment]
+1 as proposed

**Comment by rowenaluk** [comment]
+1 to justin

**Comment by mberg** [comment]
Support a default limit.
Support returning total count in result set
limit=off

**Comment by edjez** [comment]
+1 to this

**Comment by mberg** [comment]
Incorporated in 1.1 docs. Close for now.
