### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by mberg** [facilityregistry/fred-api#22]
# Sorting

```
/facilities.json?sortAsc=beds&sortDesc=nurses
```

Sorts the results by property.  

.. Note:: 
-  Each field type needs to define what ascending/descending means.
  - Sorting precedence is left to right (first by beds then by nurses in the example above) - closest to the “?”

**Comment by mwhite** [comment]
I'm not a huge fan of sorting precedence being based on the order of the GET parameters.  It constrains provider and consumer implementation a bit, making them operate at the URL-string level instead of a simple parameter mapping.

**Comment by edjez** [comment]
Lets support 1 field for now

**Comment by mberg** [comment]
Limit sort by 1 for now.

**Comment by mberg** [comment]
Incorporated in 1.1 docs. Close for now.
