### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by mberg** [facilityregistry/fred-api#23]
# Filtering Facilities

```
/facilities.json?property1=value&property2=value
```

Properties apply to all core and user defined facility properties

**Comment by ghost** [comment]
+1 for filtering. To keep it simple for 1.1 I would probably enforce some basic rules. Here are some thoughts:
- Exact matches only (for 1.1.0)
- One value per instance of parameter
- Instances of the same parameter are OR and different are AND.
- Name of a parameter must exactly match the name of the property (core or extended) on which it filters data

For example: ?properties.services=OBG&properties.services=ER would filter all facilities offering OBG OR ER, where as ?identifiers.id=2030&identifiers.agency=MOH would filter facilities with an identifier 2030 AND identifier assigned by MOH.

Pattern matches can perhaps be controlled by a control parameter of ?matching=exact or ?matching=pattern with the default being "exact". This way you can roll pattern matching into 1.2 and it would still be backwards compatible with 1.1 & 1.0. Also this leads a future pathway to other matching algorithms such as ?matching=soundex or ?matching=geobounds

**Comment by mberg** [comment]
implementing justin's suggestions

**Comment by mberg** [comment]
For now we only support exact matches.

**Comment by edjez** [comment]
Not a huge fun of properties. 'namespaces' but OK with it to help consensus

**Comment by mberg** [comment]
Incorporated in 1.1 docs. Close for now.
