### ISSUE TITLE
Improve language re JSON

### ISSUE THREAD

**Issue by bobjolliffe** [facilityregistry/fred-api#29]
The spec currently says:
"The initial API implementation will support only JSON. Once the API stabilizes, support for an XML endpoint is planned."

It is pointlerss making reference to things like the "initial API implementation".  At some point in the future someone will just be looking at this document.  So we keep it simple.  What we mean is:
"This document defines an API which uses JSON (http://www.json.org).for exchanging data."

What is planned or not planned is not really helpful to understand this document.  But if anywhere, future plans  should be in "Future API Features" section.

(In a separate issue I will propose dropping that section anyway.  it is highly unusual to highlight the features of the next version of a spec in the current version.  For good reason.)

**Comment by edjez** [comment]
agree

**Comment by mberg** [comment]
updated thanks
