### ISSUE TITLE
Return more data on facility creation

### ISSUE THREAD

**Issue by mwhite** [facilityregistry/fred-api#37]
Currently the spec says that the server should return the facility URL when a facility is created. (DHIS2 does this with the Location header.  This should probably be explicitly specified in the spec.)

DHIS2 also returns the URL of a human-readable page.  Since there is no defined format for URLs with respect to IDs, there is no way to get the ID of a newly created facility.

The spec should be changed to either:
- the URL returned must be to the JSON representation of the facility.  The client can then make an additional request to get data about the new facility.
- or better, the response body should contain the JSON representation of the core properties of the facility.  This also ensures that other core properties like createdAt and updatedAt are known to the client.

**Comment by mortenoh** [comment]
I agree. For POST/PUT we should return the updated facility as JSON.

We have a specific need for this in Uganda, where we are generating ETag to
help with edit conflicts.

## 

Morten

**Comment by mortenoh** [comment]
We still want to also return the Location header of course.

**Comment by rowenaluk** [comment]
+1

**Comment by mortenoh** [comment]
DHIS 2 have already been updated to return the body as JSON both in POST and PUT, this helps with ETag generation (which is not part of the spec, but we are using it in Uganda).

We also set the Location: header as an absolute URL, and return the code 201 Created.

Unless someone disagree, I think we should close this, and put it as part of the spec.

**Comment by mberg** [comment]
Mortan we discussed this specific issue on the last call and are going to
do this. 201 created with location pointing to the created resource.

I'll be doing a lot of cleanup on the docs today working from.  Trying to
get everything up to date with the github issues.

Will be working form this (still missing a few updates like the 201,  what
are the required parameters in the creates etc).

http://facility-registry-api.readthedocs.org/en/latest/api_1_1.html

Will send a summary later today when this is all completed.

On Sun, Feb 3, 2013 at 9:02 AM, Morten Olav Hansen <notifications@github.com

**Comment by edjez** [comment]
Can be closed- obsolete

**Comment by mberg** [comment]
Closing for Ed
