### ISSUE TITLE
put and posts

### ISSUE THREAD

**Issue by mberg** [facilityregistry/fred-api#39]
Return the feature in the response

**Comment by ctford** [comment]
What do you mean by "the feature"?

**Comment by bobjolliffe** [comment]
I think this is a georss hangover.  You mean the facility?

**Comment by mberg** [comment]
This is a remnant as GeoJson entities are called features.

Facilities are referred to as facility objects or collection of facilities now.

http://facilityregistry.org/#create-facility

**Comment by edjez** [comment]
"a georss hangover."
Ha Bob. You couldn't resist I see...

**Comment by edjez** [comment]
Close as obsolete. Also like that we return in the response and not a redirect

**Comment by mberg** [comment]
closed
