### ISSUE TITLE
Discuss whether IDs should be changeable on updates

### ISSUE THREAD

**Issue by mberg** [facilityregistry/fred-api#41]
Ed's personal vote is it's not needed

**Comment by mwhite** [comment]
All agreed that they should not be changeable.

**Comment by edjez** [comment]
agreed internal IDs should not be editable
(user IDs with the context/agency of course should be)

**Comment by ghost** [comment]
Is there a use case for merging facility records (like in a client registry)? That is the only time that I would see an identifier being replaced/changed to another.

**Comment by ctford** [comment]
@justin-fyfe1, I think we would need to explicitly think about how to handle merges. Changing ids won't in itself be enough for clients to understand what has been merged with what.

**Comment by edjez** [comment]
Ready to close - docs already say "the id, url, createdAt, and updatedAt core properties cannot be changed by the client"

**Comment by mberg** [comment]
Closing.
