### ISSUE TITLE
Define what results in a duplicate facility 409 - Conflict response

### ISSUE THREAD

**Issue by mwhite** [facilityregistry/fred-api#43]
The spec for create currently says: "If duplicate is detected a 409 is returned"

but doesn't define what a duplicate is.

I think one of the provider implementations I've been testing against considered having the same name to be enough to consider a facility a duplicate, but that doesn't seem robust.

Same name and coordinates?

Is it left up to the implementation? If so, that should be stated.

**Comment by ghost** [comment]
I think this was mentioned in the formal document, however it might have been overlooked while migrating content over to the wiki format.

Matt: There is some sample verbiage in the formal document on pages 15-16 (near line 310) which mentions this. If you like this can be recycled into the wiki (or massaged a little).

**Comment by edjez** [comment]
This should cover At Least, mandatorily, when there are duplicate UUIDs

**Comment by rowenaluk** [comment]
Resolution: let's update the documentation to be clear on this. A 'duplicate response' MUST be provided in the case of duplicate UUIDs. However, it is up to the implementation to decide if there are additional duplicate-detection algorithms that they want to apply on top of this. For example, some provider registries might reject duplicate GPS coordinates or names, while some might not.
