### ISSUE TITLE
Rename url => href

### ISSUE THREAD

**Issue by mortenoh** [facilityregistry/fred-api#46]
I think the url field should be renamed to href, this will keep it more in sync with what people are used to from other APIs.

**Comment by bobjolliffe** [comment]
+1

I guess this is also making explicit that the url should use http or https
scheme, rather than file://, ftp:// or what have you.  I think its a minor
improvement.

**Comment by mortenoh** [comment]
I agree.

**Comment by edjez** [comment]
ok

**Comment by rowenaluk** [comment]
+1

**Comment by rowenaluk** [comment]
resolved on march 7 call

**Comment by rowenaluk** [comment]
no objections from anyone

**Comment by mberg** [comment]
Please don't close these until the api is updated to reflect these changes..  Updating API now.
