### ISSUE TITLE
Default value of active (true)

### ISSUE THREAD

**Issue by mortenoh** [facilityregistry/fred-api#47]
Hi

In the current spec, it says that only name is required. But it does not give the default value for active. I'm assuming this is `true` ? If so, it should be in the spec.

**Comment by rowenaluk** [comment]
+1

**Comment by edjez** [comment]
OK Active  = true is the default

**Comment by rowenaluk** [comment]
no objections on the march 7 call

**Comment by mberg** [comment]
http://facilityregistry.org/#create-facility
