### ISSUE TITLE
Paging: rename limit=off to limit=0

### ISSUE THREAD

**Issue by mortenoh** [facilityregistry/fred-api#49]
I suggest this so that we have less confusion. Right now its hard to understand what limit=off means with regards to the offset parameter.

I suggest limit=0 means no limit.

**Comment by sunbiz** [comment]
+1

**Comment by edjez** [comment]
In general I don't like magic numbers - in this case Limit=0 means limit=infinite
how about ?paging=false

**Comment by edjez** [comment]
From Morten: Also we need to specify what happens if you have limit=off, and then specify an offset, (ie return all records starting at offset)

**Comment by mortenoh** [comment]
I prefer `paging=false` to `limit=off`

**Comment by edjez** [comment]
Folks add comments with your opinions so we can rapidly close this one.

**Comment by mberg** [comment]
limit=off
