### ISSUE TITLE
errorMessage.code can be a number?

### ISSUE THREAD

**Issue by mortenoh** [facilityregistry/fred-api#50]
Hi

It seems that in the spec message.code is required to be a string, since both the status code + status message is used.

Can/should this be changed to only status code? it makes sense, yes? If you want to say, "bla bla not found" you can do so in the message part.

**Comment by ctford** [comment]
But aren't status codes still strings? i.e. "200", not 200. You don't ever multiply or add them, for example.

**Comment by mortenoh** [comment]
I guess that's true. Don't feel strongly either way on it, just using the
"CODE" should be fine.

## 

Morten

**Comment by edjez** [comment]
Close as obsolete.

**Comment by mberg** [comment]
Allow code and message to be custom.  Fix to make it valid json

**Comment by mortenoh** [comment]
I still think calling it a "error message" is wrong. The code should be what defines whether it is an informational service (as in when we are deleting) or an error.

**Comment by edjez** [comment]
Yup, the text just says "the message" now.
