### ISSUE TITLE
In Create Facility spec, issue with required fields

### ISSUE THREAD

**Issue by edjez** [facilityregistry/fred-api#51]
It says:
_The body can’t be empty and must include at least the name attribute, a string that will be used as the name of the facility._

One would expect it to say: the body can avoid the name attribute if it has other stuff. Of course hopefully people would not send an empty document.

**Comment by ctford** [comment]
My interpretation of the above is just that "name is mandatory". Are you interpreting it as "there must be at least one field present"?

**Comment by edjez** [comment]
Sorry. "name is mandatory" is a simpler and clearer way of saying it.

**Comment by mberg** [comment]
Updated
