### ISSUE TITLE
Clarification : Delete

### ISSUE THREAD

**Issue by ghost** [facilityregistry/fred-api#6]
Hello All,

I'm just requesting some clarification/suggestion on one of the operations in the FRED operation contract. The DELETE verb in the API docs posted on the internet it states that DELETE deletes a registry from the facility registry. 

May I suggest that we dont use this verbiage in the formal documentation and instead refer to it as an obsoletion (or logical deletion). My rationale is two fold on this:
1. You should never actually delete data that can be linked from another service. For example, if I have a provider registry which links to facility 123 on a FRED instance as "primary place of work", and some other system deletes 123 on the FRED instance, my data is not inconsistent.
2. Obsoletion is more often used in most other registries and is more consistent with existing standards.

What I am proposing in the formal documentation is that obsoleted facilities should not be discoverable (i.e. should not be returned in queries), however should be retrievable via a direct GET against the resource. I have not specified how this is to be done internally, however at a wire level the operation should use the DELETE verb (it is a logical deletion).

Cheers
-Justin

**Comment by bobjolliffe** [comment]
We already have a means of marking facilities inactive.  This would be done
with an update on the facility entry.

There are cases, particularly in the early stages of setting up a registry
where you would want to delete facilities.  We also see cases where there
are facilities called "Test Clinic" or unused duplicates.  So I don't think
we should remove the operation to delete a facility, but leave it to the
application to ensure that this operation is properly handled (and
secured).

**Comment by mberg** [comment]
Justin,

I think that sounds good.  We hadn't really given this a lot of thought on how the specifics of the DELETE would work yet.

Agree going obsoletion vs. deleting is probably the way to go.

**Comment by mberg** [comment]
Actually just read Bob's post and agree that we will need DELETE ability to cleanup in the beginning and we should just highlight that marking the status as inactive is preferable to deletion.  I was thinking that is what you meant by obsoleltation earlier.  On the implementation side, one might chose to not actually delete records but that should probably be left to the decision of the implementer at this point.

**Comment by ghost** [comment]
Hi Bob,

I think there is a semantic difference between updating a facility to be inactive vs. obsoletion. Obsoletion would be a logical delete where the facility would no longer show up in queries, but could still be retrieved via direct GET perhaps returning a 410 Gone HTTP error code, rather than the resource just disappearing with a 404 (the client has more information). 

I think we need to specify some behavioral rules around DELETE as this potentially has consequences on other consumer systems. 

Cheers
-Justin

**Comment by bobjolliffe** [comment]
I think you are getting too complicated.  The practice in the field is to
simply mark the active field to false when a facility entry is
"deactivated".  You can draw subtle distinctions between obsolete and
inactive but in practice in our context we have not seen the need.

**Comment by ghost** [comment]
Ok, here is the verbiage I am using. Perhaps I should include additional verbiage that directs client implementers to utilize the update/active mechanism and restrict delete operations for records created in error?

When the facility registry receives a request to obsolete a facility, the facility registry SHALL validate that the facility exists. If the requested target of deletion does not exist, the facility registry SHALL respond with an HTTP 404 error.

If the facility resource exists, the facility registry SHALL delete the facility resource such that the record is no longer discoverable to consumers. The process by which the facility registry marks the facility as deleted is not specified in this document, and is left to implementers to determine the most appropriate method.

Once the record is deleted, the facility registry SHALL return an HTTP 200 response with the URL of the deleted facility.

**Comment by mwhite** [comment]
The documentation should specify what should happen when you try to update a deleted/deactivated facility.

**Comment by mortenoh** [comment]
Why would it need to specify that? updating a deleted facility, is the same as updating a non-existent facility, so this should just return a 404.

**Comment by ghost** [comment]
Semantically speaking, they are two different things. 404 means something wasn't found and doesn't provide any additional information (did it never exist? was is deleted?), whereas something that did exist and is now gone should technically return 410 (gone) signalling that the resource you asked for no longer exists. 

410 is probably the best behavior, however we felt it would be quite prescriptive of how the registry handles deleted items (in our HL7v3 FR there is no delete operation, only obsolete so this would be possible but other implementations may just delete the data). I believe the formal doc verbiage has changed from the above post ;)

Cheers

**Comment by mortenoh** [comment]
Yes, I agree with that. But that would also mean that the delete part of the spec should be updated (keep history, do not reuse IDs), which is fine I guess.

**Comment by edjez** [comment]
Ok ready to close - reflected in API

**Comment by mberg** [comment]
already reflected in API
