### ISSUE TITLE
Move MOH_ID, UNICEF_ID, X_ID to just ID

### ISSUE THREAD

**Issue by ghost** [facilityregistry/fred-api#8]
Hello Again,

When doing the formal documentation draft I encountered the MOH_ID, UNICEF_ID elements and thought this seems like a rather odd way of representing muliple identifiers. I would propose that these be consolodated as "identifiers" or simple "id" with the agency element populated. 

The rationale behind this is simple best practices when programming. Rarely do programmers write code fields: home_address, work_address, work2_address, etc. rather it is better practice to create an array of address with a type classifier. My suggestion is change:

<moh_id agency="moh" id="123"/>
<unicef_id agency="unicef" id="321"/>

to 

<id agency="moh" id="123"/>
<id agency="unicef" id="321"/>

This solution is much cleaner and is closer to existing standards.

Cheers
-Justin

**Comment by mberg** [comment]
Justin the examples are blank.  You need to indent 4 spaces.  You mean something like this right?  I think earlier the thought was to leverage xpaths but I think this looks cleaner too.

```
<id agency="UNICEF">1234</id>
```

**Comment by bobjolliffe** [comment]
Hi Justin

This is one of those examples of discussion which has oscillated back and
forth in response to feedback on list.  I believe the last resolution was
to revert (as you suggest below) to the the grouped identifiers as
https://github.com/facilityregistry/samples/blob/master/rm.xml and
https://github.com/facilityregistry/samples/blob/master/facility.xsd.

Bob

**Comment by mberg** [comment]
Do we want to keep using identities/identity or move to using ids / id?

If we move to id.  What do we want to denote the system id?  Would that be in this ID block or above?  If we keep it in this block do we want to use agency=system?

```
<identities> <!-- mandatory -->
    <id>http://facilities.moh.gov.rw/api/sites/50181.rss</guid> <!-- mandatory -->
    <identity agency="MOH" context="HMIS" id="ffghf5fghf5" /> <!-- optional -->
    <identity agency="MOH" context="HR" id="567" /> <!-- optional -->
    <identity agency="MOH" context="FOSA" id="208" /> <!-- optional -->
</identities>
```

**Comment by ghost** [comment]
I'd be ok with either using a repeating <id> element with an agency of "system", or perhaps an alternate would be an <id> element with the system assigned identifier and a repeating <otherId> element for alternate identifiers which are informational (this is how IHE PIX does it) for example:

<id>http://yyyyyy/zzz</id>
<otherId agency="MOH" context="HMIS" id="432"/>
<otherId agency="MOH" context="HR" id="123"/>

I think minimizing the nesting would be good for implementers and makes the schema look a little cleaner, these elements could be children of the <facility> resource.

**Comment by ghost** [comment]
woops.. it looks like my tags were erased, looks like I need to go to github school ;)

What I meant to say was the repeating `<id>` element with agency "system" is good, but we could also use `<id>` for the system assigned identifier(s) and `<otherId>` for the alternate identifiers. For example:

`<id>urn:oid:1.2.3.4.5.103945</id>`
`<otherId context="DHIS" agency="MOH" id="1234"/>`
`<otherId context="HR" agency="MOH" id="4321"/>`

**Comment by ctford** [comment]
Just so long as for the (possible) JSON format we make repeated elements a first-class collection and not implicitly bundle them together by having a bunch of elements, some of which have `identifier="true"` or `type="..."` ie not:

```
[
  {type="id" urn="urn:oid:1.2.3.4.5.103945"}
  {type="otherId" context="DHIS" id="1234"}
  {type="otherId" context="HR" id="4321"}
]
```

The above is annoying to process. :-)

**Comment by bobjolliffe** [comment]
That doesn't look like what justin has written.

Justin I think we have agreed that there will be an internal system id
element, a url element and then a collection <identities> of <identity>
elements

**Comment by ghost** [comment]
Hi Bob, the schema has guid and url properties (which I've put into the document), what I was suggesting (and I think Matt was asking) was if we want to collapse out the `<identities>` element and instead just have all identities as child nodes of the facility. Maybe something like this:

```
<url>http://xx.yyy.zzz/123</url>
<guid>urn:uuid:304938594-0349584...</guid>
<identity context="DHIS" agency="MOH" id="123"/>
<identity ... />
```

I'm ok with using the `identities` element, collapsing XML was just a suggestion :). Also, I think we should harmonize the schema with the API 0.9 XML samples/doc. I'm ok with taking a crack at it if others don't have the cycles. 

Chris, I've been focusing on XML for the formal spec but am writing an informative JSON representation of the XML structures identified in the document. I am ok with any JSON representation the group comes up with as long as I can show how data is mapped from one to another (need to think from a data architect's view, especially somone coming from outside our fishbowl ;) ). A 1-to-1 map in JSON would be :

```
 url : "http://xx.yyy.zzz/123",
 guid : "urn:uuid:....",
 identity : [
       { agency : "MOH", context : "DHIS", id : "123" },
       { .... }
 ]
```

I know this might be little harder to process using JS, we may end up suggesting that JSON implementations group identifiers by agency:

```
  identity : {
          MOH : [
                { context : "DHIS", id : "123" },
                { ... }
          ], 
          UNICEF : [
```

Or some other useful JSON structure...

Thanks all for the discussions, it is helping me organize my thoughts so I can reflect it in the spec document.

Cheers
-Justin

**Comment by edjez** [comment]
Sad to see the standalone fields with "identifier" flag gone.. but OK.
I would name the array "identifiers" not "identity"
I would keep the system ID outside, in an "id" field (not the full URL)

**Comment by mberg** [comment]
URL: full path to the ID
id: just the GUID / system ID

We use the identifiers for the ID array.

**Comment by edjez** [comment]
Ready to be closed - obsoleted by recent and older id discussions
