### ISSUE TITLE
Suggest servers support gzip, etags and cache headers

### ISSUE THREAD

**Issue by ctford** [facilityregistry/fred-api#9]
We don't need to make this mandatory, but from our conversations on the other issues it seems that bandwidth usage is a common concern. These three standard HTTP elements can cut down on unnecessary data transfer.

They can be suggestions rather than mandatory, and standard HTTP request headers will let servers and clients take advantage of these features assuming both support it. In fact, servers could very well decide to provide these features under the current spec.

Cache headers especially could be useful, as a common use case seems to be maintaining a mirror of facility information.

**Comment by rowenaluk** [comment]
+1

**Comment by edjez** [comment]
+1

**Comment by rowenaluk** [comment]
All agree that these are good suggestions to make, and should be included as best practices in our documentation, but are not mandatory.
